CREATE TABLE PRODUCTS(id INT PRIMARY KEY, name VARCHAR(255), image_path VARCHAR(255));
CREATE TABLE USERS(USERNAME VARCHAR(255), PASSWORD VARCHAR(255), FIRST_NAME VARCHAR(255), LAST_NAME VARCHAR(255), AGE INT, ACTIVITY VARCHAR(255));
